<h1 style='text-align:center'>Machine Learning Assingment 6 <br><h2 style="text-align:center">Felix Filipi-2301877590</h2><h1>

<h3>Import Dataset</h3>

In [1]:
import pandas as pd

ds=pd.read_csv('datasets/listings.csv')

ds

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,49091,COZICOMFORT LONG TERM STAY ROOM 2,266763,Francesca,North Region,Woodlands,1.44255,103.79580,Private room,83,180,1,2013-10-21,0.01,2,365
1,50646,Pleasant Room along Bukit Timah,227796,Sujatha,Central Region,Bukit Timah,1.33235,103.78521,Private room,81,90,18,2014-12-26,0.28,1,365
2,56334,COZICOMFORT,266763,Francesca,North Region,Woodlands,1.44246,103.79667,Private room,69,6,20,2015-10-01,0.20,2,365
3,71609,Ensuite Room (Room 1 & 2) near EXPO,367042,Belinda,East Region,Tampines,1.34541,103.95712,Private room,206,1,14,2019-08-11,0.15,9,353
4,71896,B&B Room 1 near Airport & EXPO,367042,Belinda,East Region,Tampines,1.34567,103.95963,Private room,94,1,22,2019-07-28,0.22,9,355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7902,38105126,Loft 2 pax near Haw Par / Pasir Panjang. Free ...,278109833,Belle,Central Region,Queenstown,1.27973,103.78751,Entire home/apt,100,3,0,NaN,NaN,31,61
7903,38108273,3bedroom luxury at Orchard,238891646,Neha,Central Region,Tanglin,1.29269,103.82623,Entire home/apt,550,6,0,NaN,NaN,34,365
7904,38109336,[ Farrer Park ] New City Fringe CBD Mins to MRT,281448565,Mindy,Central Region,Kallang,1.31286,103.85996,Private room,58,30,0,NaN,NaN,3,173
7905,38110493,Cheap Master Room in Central of Singapore,243835202,Huang,Central Region,River Valley,1.29543,103.83801,Private room,56,14,0,NaN,NaN,2,30
7906,38112762,Amazing room with private bathroom walk to Orc...,28788520,Terence,Central Region,River Valley,1.29672,103.83325,Private room,65,90,0,NaN,NaN,7,365

<h3>Apply pandas factorize ke data</h3>

In [2]:
ds=ds.apply(lambda ds : pd.factorize(ds)[0])
ds

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,0
2,2,2,0,0,0,0,2,2,0,2,2,2,2,2,0,0
3,3,3,2,2,2,2,3,3,0,3,3,3,3,3,2,1
4,4,4,2,2,2,2,4,4,0,4,3,4,4,4,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7902,7902,7452,2615,995,1,10,4882,5368,1,22,9,16,-1,-1,54,162
7903,7903,7453,2258,1573,1,17,4883,5412,1,56,2,16,-1,-1,53,0
7904,7904,7454,2639,1346,1,19,655,3557,0,45,5,16,-1,-1,6,15
7905,7905,7455,2571,1744,1,7,4332,5413,0,17,19,16,-1,-1,0,266
7906,7906,7456,2161,1521,1,7,4884,5265,0,13,1,16,-1,-1,12,0

<h2>1. Discuss to find the correlation and covariance of the data (the variables used can be categorical vs categorical, categorical vs numeric, or numeric vs numeric variables) </h2>

In [3]:
ds.corr(method='pearson')

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
id,1.000000,0.988022,0.653095,0.448236,-0.118757,-0.000598,0.638238,0.709132,0.132164,0.195642,0.076483,-0.274454,-0.174398,0.017247,0.319351,0.172010
name,0.988022,1.000000,0.659173,0.458965,-0.116286,-0.007139,0.631376,0.703299,0.127614,0.190264,0.073680,-0.267213,-0.167006,0.026550,0.307484,0.170612
host_id,0.653095,0.659173,1.000000,0.743178,0.019277,0.007650,0.478345,0.517695,0.047579,0.116249,-0.051798,-0.156048,-0.101621,0.080998,0.090118,0.149642
host_name,0.448236,0.458965,0.743178,1.000000,-0.002900,-0.015973,0.317035,0.347062,0.049723,0.074749,-0.012852,-0.115918,-0.067326,0.029996,0.155004,0.054345
neighbourhood_group,-0.118757,-0.116286,0.019277,-0.002900,1.000000,0.192088,0.010494,-0.002843,-0.219314,-0.106744,-0.048565,-0.026434,0.039952,-0.045373,-0.219835,-0.058268
neighbourhood,-0.000598,-0.007139,0.007650,-0.015973,0.192088,1.000000,0.086661,-0.026223,0.017158,0.067810,0.040260,-0.059813,0.012347,-0.038201,-0.021364,-0.038455
latitude,0.638238,0.631376,0.478345,0.317035,0.010494,0.086661,1.000000,0.485070,0.065457,0.138667,0.050584,-0.176747,-0.072949,0.011873,0.166177,0.124792
longitude,0.709132,0.703299,0.517695,0.347062,-0.002843,-0.026223,0.485070,1.000000,0.064306,0.120018,0.044670,-0.188467,-0.083190,0.029811,0.203567,0.139829
room_type,0.132164,0.127614,0.047579,0.049723,-0.219314,0.017158,0.065457,0.064306,1.000000,0.275265,0.099430,-0.002748,-0.019324,0.002210,0.341815,0.054280
price,0.195642,0.190264,0.116249,0.074749,-0.106744,0.067810,0.138667,0.120018,0.275265,1.000000,0.023219,-0.035500,-0.061110,0.001418,0.221822,0.061821
minimum_nights,0.076483,0.073680,-0.051798,-0.012852,-0.048565,0.040260,0.050584,0.044670,0.099430,0.023219,1.000000,-0.085439,-0.028492,-0.116017,0.156165,-0.061709
number_of_reviews,-0.274454,-0.267213,-0.156048,-0.115918,-0.026434,-0.059813,-0.176747,-0.188467,-0.002748,-0.035500,-0.085439,1.000000,-0.053950,0.447557,-0.107685,0.181124
last_review,-0.174398,-0.167006,-0.101621,-0.067326,0.039952,0.012347,-0.072949,-0.083190,-0.019324,-0.061110,-0.028492,-0.053950,1.000000,0.033488,-0.073475,-0.058830
reviews_per_month,0.017247,0.026550,0.080998,0.029996,-0.045373,-0.038201,0.011873,0.029811,0.002210,0.001418,-0.116017,0.447557,0.033488,1.000000,-0.116761,0.285293
calculated_host_listings_count,0.319351,0.307484,0.090118,0.155004,-0.219835,-0.021364,0.166177,0.203567,0.341815,0.221822,0.156165,-0.107685,-0.073475,-0.116761,1.000000,0.036041
availability_365,0.172010,0.170612,0.149642,0.054345,-0.058268,-0.038455,0.124792,0.139829,0.054280,0.061821,-0.061709,0.181124,-0.058830,0.285293,0.036041,1.000000

In [4]:
ds.cov()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
id,5.210713e+06,4.840917e+06,1.197171e+06,559058.476347,-220.782317,-11.610928,2.021881e+06,2.495105e+06,174.553124,32358.805085,1494.011637,-19925.072856,-104039.412219,4440.629901,12383.185429,35582.503795
name,4.840917e+06,4.607074e+06,1.136168e+06,538261.610637,-203.282070,-130.233876,1.880722e+06,2.326836e+06,158.481333,29590.314982,1353.329568,-18241.140117,-93681.011875,6428.004702,11211.178096,33186.034632
host_id,1.197171e+06,1.136168e+06,6.448543e+05,326080.715641,12.607161,52.213162,5.330850e+05,6.407936e+05,22.105937,6763.946047,-355.950464,-3985.382416,-21326.507592,7336.692481,1229.299951,10889.768167
host_name,5.590585e+05,5.382616e+05,3.260807e+05,298540.498929,-1.290558,-74.177889,2.403989e+05,2.922950e+05,15.719045,2959.281014,-60.092812,-2014.349968,-9613.685309,1848.658684,1438.667608,2690.870343
neighbourhood_group,-2.207823e+02,-2.032821e+02,1.260716e+01,-1.290558,0.663308,1.329643,1.186149e+01,-3.569626e+00,-0.103345,-6.299134,-0.338475,-0.684692,8.503518,-4.168162,-3.041379,-4.300501
neighbourhood,-1.161093e+01,-1.302339e+02,5.221316e+01,-74.177889,1.329643,72.236006,1.022169e+03,-3.435386e+02,0.084372,41.758886,2.928154,-16.167970,27.424271,-36.622391,-3.084386,-29.618268
latitude,2.021881e+06,1.880722e+06,5.330850e+05,240398.928356,11.861485,1022.168765,1.925965e+06,1.037629e+06,52.558626,13943.678258,600.730031,-7801.112607,-26457.805605,1858.509776,3917.514293,15694.438587
longitude,2.495105e+06,2.326836e+06,6.407936e+05,292295.038214,-3.569626,-343.538647,1.037629e+06,2.375890e+06,57.349650,13404.164545,589.217067,-9239.100885,-33511.166167,5183.055121,5330.106427,19531.850329
room_type,1.745531e+02,1.584813e+02,2.210594e+01,15.719045,-0.103345,0.084372,5.255863e+01,5.734965e+01,0.334760,11.539790,0.492298,-0.050573,-2.921907,0.144235,3.359496,2.846014
price,3.235881e+04,2.959031e+04,6.763946e+03,2959.281014,-6.299134,41.758886,1.394368e+04,1.340416e+04,11.539790,5250.027430,14.396668,-81.806007,-1157.185350,11.591929,273.024908,405.926683
minimum_nights,1.494012e+03,1.353330e+03,-3.559505e+02,-60.092812,-0.338475,2.928154,6.007300e+02,5.892171e+02,0.492298,14.396668,73.229385,-23.253116,-63.720641,-111.984470,22.700839,-47.854360
number_of_reviews,-1.992507e+04,-1.824114e+04,-3.985382e+03,-2014.349968,-0.684692,-16.167970,-7.801113e+03,-9.239101e+03,-0.050573,-81.806007,-23.253116,1011.493002,-448.417827,1605.549807,-58.177303,522.023551
last_review,-1.040394e+05,-9.368101e+04,-2.132651e+04,-9613.685309,8.503518,27.424271,-2.645781e+04,-3.351117e+04,-2.921907,-1157.185350,-63.720641,-448.417827,68299.137354,987.161159,-326.186369,-1393.281991
reviews_per_month,4.440630e+03,6.428005e+03,7.336692e+03,1848.658684,-4.168162,-36.622391,1.858510e+03,5.183055e+03,0.144235,11.591929,-111.984470,1605.549807,987.161159,12722.940740,-223.721981,2916.209103
calculated_host_listings_count,1.238319e+04,1.121118e+04,1.229300e+03,1438.667608,-3.041379,-3.084386,3.917514e+03,5.330106e+03,3.359496,273.024908,22.700839,-58.177303,-326.186369,-223.721981,288.557499,55.481265
availability_365,3.558250e+04,3.318603e+04,1.088977e+04,2690.870343,-4.300501,-29.618268,1.569444e+04,1.953185e+04,2.846014,405.926683,-47.854360,522.023551,-1393.281991,2916.209103,55.481265,8212.328810

 <h2>2. Normalized the data using Standardization or Range Scaling method. (MaxAbsScaler)</h2>

In [5]:
from sklearn.preprocessing import MaxAbsScaler

scaled=MaxAbsScaler().fit_transform(ds)
data=pd.DataFrame(scaled,columns=ds.columns)
data

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,0.000000,0.000000,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000
1,0.000126,0.000134,0.000370,0.000546,0.25,0.023810,0.000205,0.000185,0.0,0.002681,0.013889,0.004831,0.001,0.001901,0.018519,0.000000
2,0.000253,0.000268,0.000000,0.000000,0.00,0.000000,0.000410,0.000369,0.0,0.005362,0.027778,0.009662,0.002,0.003802,0.000000,0.000000
3,0.000379,0.000402,0.000740,0.001092,0.50,0.047619,0.000614,0.000554,0.0,0.008043,0.041667,0.014493,0.003,0.005703,0.037037,0.002793
4,0.000506,0.000536,0.000740,0.001092,0.50,0.047619,0.000819,0.000739,0.0,0.010724,0.041667,0.019324,0.004,0.007605,0.037037,0.005587
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7902,0.999494,0.999464,0.967086,0.543122,0.25,0.238095,0.999590,0.991687,0.5,0.058981,0.125000,0.077295,-0.001,-0.001901,1.000000,0.452514
7903,0.999621,0.999598,0.835059,0.858624,0.25,0.404762,0.999795,0.999815,0.5,0.150134,0.027778,0.077295,-0.001,-0.001901,0.981481,0.000000
7904,0.999747,0.999732,0.975962,0.734716,0.25,0.452381,0.134111,0.657122,0.0,0.120643,0.069444,0.077295,-0.001,-0.001901,0.111111,0.041899
7905,0.999874,0.999866,0.950814,0.951965,0.25,0.166667,0.886978,1.000000,0.0,0.045576,0.263889,0.077295,-0.001,-0.001901,0.000000,0.743017
7906,1.000000,1.000000,0.799186,0.830240,0.25,0.166667,1.000000,0.972658,0.0,0.034853,0.013889,0.077295,-0.001,-0.001901,0.222222,0.000000

<h2>3. Do feature selection and extraction. </h2>

<h3>Untuk mengetahui berapa dimensi yang kita perlukan kita dapat melihat variance tiap attribute </h3>

In [6]:
from sklearn.decomposition import PCA

pca=PCA()
data=pca.fit_transform(data)
pca.explained_variance_ratio_

array([0.34475513, 0.12248205, 0.07728637, 0.07662412, 0.06594116,
       0.05674411, 0.04768792, 0.03927429, 0.03728744, 0.03280294,
       0.02988133, 0.02510284, 0.01695519, 0.01354867, 0.01268241,
       0.00094403])

<h3>Setelah mengecek variancenya, kita dapat tentukan dimension reduction yang tepat (saya ambil 12 attribute saja dan membuang 4 attribute terakhir)</h3>

In [7]:
pca=PCA(n_components=12)
data=pca.fit_transform(data)
pd.DataFrame(data,columns=ds.columns[0:12])

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews
0,-1.178594,0.083037,-0.035609,-0.166871,-0.348760,-0.120061,-0.415586,-0.228278,-0.191317,0.027984,-0.047052,-0.063399
1,-1.182621,0.124227,-0.052074,-0.198525,-0.337009,-0.096266,-0.284733,-0.113077,-0.148801,-0.068190,0.022190,0.049813
2,-1.178080,0.080932,-0.033645,-0.164367,-0.346897,-0.120098,-0.414651,-0.229704,-0.186010,0.030109,-0.044281,-0.064455
3,-1.186148,0.164403,-0.066115,-0.227500,-0.324243,-0.073186,-0.152652,0.001954,-0.105115,-0.163310,0.092762,0.162359
4,-1.185816,0.164260,-0.063542,-0.223946,-0.323160,-0.074013,-0.151577,0.001724,-0.103702,-0.162090,0.094887,0.161981
...,...,...,...,...,...,...,...,...,...,...,...,...
7902,1.272454,-0.352060,0.118876,-0.148276,-0.071570,-0.214799,0.082892,-0.014249,-0.111672,-0.317618,-0.095291,-0.075676
7903,1.288482,-0.323831,-0.261583,-0.302719,-0.100477,-0.073135,0.084460,-0.077162,0.159683,-0.211956,-0.087700,-0.175605
7904,0.667438,0.485460,-0.271328,-0.135004,-0.302867,-0.044895,-0.292331,0.243381,0.015507,0.366125,-0.288466,0.201056
7905,1.143972,0.678652,0.209643,0.095287,-0.137358,-0.123106,-0.117335,0.023439,-0.415415,-0.109040,-0.058943,-0.193685
7906,1.047455,0.478914,-0.074536,-0.395375,-0.140217,-0.035544,-0.222088,-0.204987,0.014702,-0.168365,-0.022414,-0.149528